import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:the_leaf_medic/folder.dart/app_colors.dart';
import 'package:the_leaf_medic/homepage.dart';
import 'package:google_fonts/google_fonts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      theme: ThemeData(
        primarySwatch: Colors.green,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: OnboardingScreen(),
    );
  }
}

class OnboardingScreen extends StatefulWidget {
  @override
  _OnboardingScreenState createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen> {
  final List<Widget> _pages = [
    IntroScreen(),
    OnboardingPage(
      title: 'Crop Disease Detection',
      description:
          'Our app can classify different crop diseases through scanning of leaves, providing you with timely and accurate information.',
      imagePath: 'assets/images/onboarding_1.png',
    ),
    OnboardingPage(
      title: 'Agrochemicals Recommendation',
      description:
          'We recommend fertilizers and pesticides based on the detected crop diseases to help you effectively manage your crops.',
      imagePath: 'assets/images/onboarding_2.jpg',
    ),
    OnboardingPage(
      title: 'Cultivation Process Info',
      description:
          'Get detailed information about the whole cultivation process, tailored to the relevant crops, to achieve better yields.',
      imagePath: 'assets/images/onboarding_3.jpg',
    ),
    OnboardingPage(
      title: 'Maps Integration',
      description:
          'Explore detailed maps integrated with our app to locate your fields, analyze soil conditions, and plan your crop management strategies more effectively.',
      imagePath: 'assets/images/mappic.jpg',
    ),
    OnboardingPage(
      title: 'Insightful Reports',
      description:
          'Access insightful reports generated by our app, providing you with valuable analytics and trends about your crops, diseases, and productivity.',
      imagePath: 'assets/images/reports.jpg',
    ),
    OnboardingPage(
      title: 'Marketplace Access',
      description:
          'Gain access to our marketplace, where you can discover a wide range of agricultural products, tools, and services to support your farming needs.',
      imagePath: 'assets/images/marketplace.png',
    ),
    CropRecommendationScreen(),
  ];

  int _currentPage = 0;

  void _onPageChanged(int index, CarouselPageChangedReason reason) {
    setState(() {
      _currentPage = index;
    });
  }

  void _skipOnboarding() {
    // Navigate to the login form or any other desired screen
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (context) => HomePage()),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          Container(
            decoration: BoxDecoration(
              image: DecorationImage(
                image: AssetImage("assets/images/timberleaf.jpg"),
                fit: BoxFit.cover,
              ),

              //        gradient: LinearGradient(
              //          begin: Alignment.topCenter,
              //          end: Alignment.bottomCenter,
              //          colors: [
              //            Color.fromRGBO(24, 43, 50, 1),
              //            Color.fromRGBO(176, 210, 106, 1),
              //            Color.fromRGBO(153, 226, 137, 1),
              //            //      AppColors.mainColor,
              //            //    AppColors.thirdcolor,
              //            //  AppColors.secondaryColor,
              //          ],
              //        ),
            ),
            child: Column(
              children: [
                SizedBox(height: 50.0),

                // Add margin from top
                Expanded(
                  child: CarouselSlider(
                    options: CarouselOptions(
                      height: double.infinity,
                      initialPage: _currentPage,
                      enableInfiniteScroll: false,
                      autoPlay: true,
                      autoPlayInterval: Duration(seconds: 3),
                      autoPlayCurve: Curves.easeInOut,
                      enlargeCenterPage: true,
                      viewportFraction: 0.8,
                      onPageChanged: _onPageChanged,
                    ),
                    items: _pages.map((page) {
                      return Builder(
                        builder: (BuildContext context) {
                          return page;
                        },
                      );
                    }).toList(),
                  ),
                ),
                SizedBox(height: 20.0), // Reduce spacing
                Row(
                  mainAxisAlignment: MainAxisAlignment
                      .spaceEvenly, // Align dots and skip link to center
                  children: [
                    Row(
                      children: _pages.asMap().entries.map((entry) {
                        int index = entry.key;
                        bool isCurrentPage = _currentPage == index;
                        return Container(
                          width: isCurrentPage ? 20.0 : 8.0,
                          height: 8.0,
                          margin: EdgeInsets.symmetric(horizontal: 4.0),
                          decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            color: isCurrentPage
                                ? Color.fromRGBO(255, 248, 220, 1)
                                : AppColors.mainColor.withOpacity(0.6),
                          ),
                        );
                      }).toList(),
                    ),
                  ],
                ),
                SizedBox(height: 20.0),
              ],
            ),
          ),
          Positioned(
            top: 40.0,
            left: 40.0,
            child: GestureDetector(
              onTap: _skipOnboarding,
              child: Text(
                'Skip',
                style: GoogleFonts.gruppo(
                  fontSize: 16,
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ),
          Positioned(
            bottom: 14.0,
            right: 40.0,
            child: GestureDetector(
              onTap: () {
                if (_currentPage < _pages.length - 1) {
                  setState(() {
                    _currentPage++;
                  });
                } else {
                  _skipOnboarding();
                }
              },
              child: Text(
                _currentPage < _pages.length - 1 ? 'Next' : 'Go!',
                style: GoogleFonts.gruppo(
                  fontSize: 16,
                  color: Colors.white,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class OnboardingPage extends StatelessWidget {
  final String title;
  final String description;
  final String imagePath;

  const OnboardingPage({
    required this.title,
    required this.description,
    required this.imagePath,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.fromLTRB(8.0, 30.0, 8.0, 10),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(24.0),
      ),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Expanded(
            flex: 1,
            child: Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(20.0),
                  topRight: Radius.circular(20.0),
                ),
              ),
              child: Padding(
                padding: const EdgeInsets.all(7.0),
                child: Image.asset(
                  imagePath,
                  fit: BoxFit.fitWidth,
                ),
              ),
            ),
          ),
          SizedBox(height: 20.0),
          Expanded(
            flex: 1,
            child: Padding(
              padding: EdgeInsets.symmetric(horizontal: 16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Text(
                    title,
                    style: GoogleFonts.gruppo(
                      fontSize: 24,
                      fontWeight: FontWeight.bold,
                      color: AppColors.mainColor,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  SizedBox(height: 13.0),
                  Text(
                    description,
                    style: TextStyle(
                      fontSize: 16,
                      color: Colors.black,
                    ),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class IntroScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return OnboardingPage(
      title: 'Cultivating Pakistan\'s Finest 12 Crops ',
      description:
          'Get ready to dive into the fascinating realm of five key crops of Pakistan: Rice, Wheat, Cotton, Corn, and Sugarcane.',
      imagePath: 'assets/images/5crops.png',
    );
  }
}

class CropRecommendationScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return OnboardingPage(
      title: 'Crops Recommendation',
      description:
          'Get personalized crop recommendations based on environmental factors and plant nutrient analysis. Optimize your crop management for better yields!',
      imagePath: 'assets/images/grow_crop.jpg',
    );
  }
}
